export { default as Home } from './pages/Home'
export { default as Blogs } from './pages/Blogs'
export { default as Blog } from './pages/Blog'
export { default as Contact } from './pages/Contact'
export { default as NewBlog } from './pages/NewBlog'
export { default as EditBlog } from './pages/EditBlog'
export { default as PageNotFound } from './pages/PageNotFound'
